# The name of bot token
Bot Token Variable Name: CLIENT_SECRET
# What file the bot token is in [be sure to include the ".py"]
Bot Token File: secrets.py

# The prefix for commands
Prefix: "BellBot "

# The "Playing ____" status of the bot
Playing Status: with some bells

# The channel ID where you want logs to go, leave blank to disable logging
Log Channel ID: 
# The channel ID where you want announcements to go
Announcements Channel ID: 
# The role ID of who you want to ping
Pinged Role ID: 

# The start of each message | "{pinged_role}" is the pinged role, which is required to be able to ping
Message Starter: "🔔 {pinged_role} 🔔"

# The settings for embeds
Embed Settings:
  # The Red/Green/Blue of the embed color
  Color:
    r: 230
    g: 126
    b: 34

# The timezone that the users of the bot will be using
User Timezone: 

# The yaml file of the block schedule
Block Calendar File: 'block-schedule.yml'

# The JSON file of the bell schedule
Bell Schedule File: 'bell-schedule.json'